### ISSUE TITLE
Numba error on pulse search

### ISSUE THREAD

**Issue by ricardovb** [StingraySoftware/HENDRICS#25]
Found issue while trying to run a pulse_search on file nu10002013003A01_cl_C_filt.evt from DAVE.
Parameters sent:
src: /Users/ricardo/Downloads/Pulsars_data_share_dave/nu10002013003A01_cl_C_filt.evt
filters [{'to': 10105, 'from': 6147, 'column': 'TIME', 'table': 'EVENTS'}]
axis [{'column': 'TIME', 'table': 'EVENTS'}, {'column': 'PHA', 'table': 'EVENTS'}]
dt 0.1
freq_range [1.39, 1.49]
mode z_n_search
oversampling 15
nharm 1
nbin 128
segment_size 5000.0

------------------------------------------------
DAVE EXCEPTION:
------------------------------------------------

Internal error at <numba.typeinfer.argconstraint object="" at="" 0x117a65cc0="">:
--%&lt;-----------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/typeinfer.py", line 189, in __call__
    assert ty.is_precise()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/typeinfer.py", line 137, in propagate
    constraint(typeinfer)
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/typeinfer.py", line 190, in __call__
    typeinfer.add_type(self.dst, ty, loc=self.loc)
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/typeinfer.py", line 189, in __call__
    assert ty.is_precise()
numba.errors.InternalError: 
[1] During: typing of argument at /Users/ricardo/TimeLab/dave/src/main/python/stingray/pulse/search.py (16)
--%&lt;-----------------------------------------------------------------

File "../../python/stingray/pulse/search.py", line 16

This error may have been caused by the following argument(s):
- argument 1: cannot determine Numba type of <class 'numpy.float128'="">
</class></numba.typeinfer.argconstraint>

-------------------------------------------------------------------------------------
SAME EXCEPTION CONSOLE OUTPUT:
-------------------------------------------------------------------------------------

Python Error: ::1 - - [2017-11-07 17:58:52] "POST /get_pulse_search HTTP/1.1" 200 2383 0.091160
ERROR:root:EXCEPTION get_pulse_search IN (/Users/ricardo/TimeLab/dave/src/main/python/utils/dave_engine.py, LINE 1664): Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.ArgConstraint object at 0x117a65cc0>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/typeinfer.py", line 189, in __call__
    assert ty.is_precise()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/typeinfer.py", line 137, in propagate
    constraint(typeinfer)
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/typeinfer.py", line 190, in __call__
    typeinfer.add_type(self.dst, ty, loc=self.loc)
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/typeinfer.py", line 189, in __call__
    assert ty.is_precise()
numba.errors.InternalError: 
[1] During: typing of argument at /Users/ricardo/TimeLab/dave/src/main/python/stingray/pulse/search.py (16)
--%<-----------------------------------------------------------------

File "../../python/stingray/pulse/search.py", line 16

This error may have been caused by the following argument(s):
- argument 1: cannot determine Numba type of <class 'numpy.float128'>

ERROR:root:Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.ArgConstraint object at 0x117a65cc0>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/typeinfer.py", line 189, in __call__
    assert ty.is_precise()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/typeinfer.py", line 137, in propagate
    constraint(typeinfer)
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/typeinfer.py", line 190, in __call__
    typeinfer.add_type(self.dst, ty, loc=self.loc)
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/Users/ricardo/TimeLab/dave/work/miniconda/envs/dave/lib/python3.5/site-packages/numba/typeinfer.py", line 189, in __call__
    assert ty.is_precise()
numba.errors.InternalError: 
[1] During: typing of argument at /Users/ricardo/TimeLab/dave/src/main/python/stingray/pulse/search.py (16)
--%<-----------------------------------------------------------------

File "../../python/stingray/pulse/search.py", line 16

This error may have been caused by the following argument(s):
- argument 1: cannot determine Numba type of <class 'numpy.float128'>

**Comment by matteobachetti** [comment]
PR here: https://github.com/StingraySoftware/stingray/pull/273
