### ISSUE TITLE
error on Pulsation searches

### ISSUE THREAD

**Issue by ktzhao** [StingraySoftware/HENDRICS#51]
Traceback (most recent call last):
  File "/home/nanograv/miniconda2/bin/HENefsearch", line 11, in <module>
    load_entry_point('hendrics==5.0.dev1198', 'console_scripts', 'HENefsearch')()
  File "/home/nanograv/miniconda2/lib/python2.7/site-packages/hendrics-5.0.dev1198-py2.7.egg/hendrics/efsearch.py", line 360, in main_efsearch
    _common_main(args, epoch_folding_search)
  File "/home/nanograv/miniconda2/lib/python2.7/site-packages/hendrics-5.0.dev1198-py2.7.egg/hendrics/efsearch.py", line 302, in _common_main
    events = load_events(fname)
  File "/home/nanograv/miniconda2/lib/python2.7/site-packages/hendrics-5.0.dev1198-py2.7.egg/hendrics/io.py", line 325, in load_events
    eventlist.time = out['time']
UnboundLocalError: local variable 'out' referenced before assignment

**Comment by matteobachetti** [comment]
Hi, thanks for the feedback. Can you tell me a little bit more? Data from
which instrument? What commands did you execute?

**Comment by ktzhao** [comment]
Sorry for disturbing.
I used the .evt file instead of the .nc file by mistake.
Thanks.

**Comment by matteobachetti** [comment]
No problem at all!
