### ISSUE TITLE
Crash with netcdf4==1.5.3

### ISSUE THREAD

**Issue by paulray** [StingraySoftware/HENDRICS#72]
I just installed on a new system and I got crashes when writing a .nc file:
```
HENreadevents --loglevel DEBUG --debug set2_2.0-8.0keV_bary.evt
Error: time_I i8 ('time_Idim',) [163856851 163856851 163856852 ... 164134794 164134794 164134796]
Traceback (most recent call last):
  File "/Software/bin/HENreadevents", line 8, in <module>
    sys.exit(main())
  File "/Software/lib/python3.6/site-packages/hendrics/read_events.py", line 234, in main
    [_wrap_fun(a) for a in arglist]
  File "/Software/lib/python3.6/site-packages/hendrics/read_events.py", line 234, in <listcomp>
    [_wrap_fun(a) for a in arglist]
  File "/Software/lib/python3.6/site-packages/hendrics/read_events.py", line 126, in _wrap_fun
    return treat_event_file(f, **kwargs)
  File "/Software/lib/python3.6/site-packages/hendrics/read_events.py", line 121, in treat_event_file
    save_events(events_filt, outfile)
  File "/Software/lib/python3.6/site-packages/hendrics/io.py", line 318, in save_events
    _save_data_nc(out, fname)
  File "/Software/lib/python3.6/site-packages/hendrics/io.py", line 752, in _save_data_nc
    save_as_netcdf(values, varnames, formats, fname)
  File "/Software/lib/python3.6/site-packages/hendrics/io.py", line 201, in save_as_netcdf
    vnc[:] = v
  File "netCDF4/_netCDF4.pyx", line 4950, in netCDF4._netCDF4.Variable.__setitem__
  File "netCDF4/_netCDF4.pyx", line 5229, in netCDF4._netCDF4.Variable._put
  File "netCDF4/_netCDF4.pyx", line 1887, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: HDF error
```

I was able to resolve this by downgrading to netcdf4==1.2.9

So, something in the new version is causing problems.

**Comment by matteobachetti** [comment]
Hi @paulray. I have netcdf4 1.5.3 on my mac and I cannot reproduce the error. Could you give me more details on your system, and maybe send me a small dataset that gives the error?

Matteo

**Comment by paulray** [comment]
This system is CentOS 7. Python 3.6.6. Here are the packages installed:
```
alabaster==0.7.11
appdirs==1.4.3
aspy.yaml==1.3.0
astropy==3.2.3
astropy-helpers==3.2.1
atomicwrites==1.1.5
attrs==19.3.0
Babel==2.6.0
backcall==0.1.0
basemap==1.2.1
beautifulsoup4==4.6.0
black==19.10b0
bleach==3.1.0
blessings==1.7
bs4==0.0.1
certifi==2018.4.16
cfgv==2.0.1
cftime==1.0.4.2
chardet==3.0.4
Click==7.0
colorama==0.4.1
configobj==5.0.6
corner==2.0.1
coverage==4.5.4
coveralls==1.8.2
cycler==0.10.0
Cython==0.28.3
decorator==4.3.0
defusedxml==0.6.0
docopt==0.6.2
docutils==0.14
emcee==3.0.1
entrypoints==0.3
fancycompleter==0.8
filelock==3.0.12
flake8==3.7.9
flake8-diff==0.2.2
flake8-docstrings==1.5.0
flake8-polyfill==1.0.2
flake8-rst-docstrings==0.0.11
future==0.16.0
gitdb2==2.0.6
GitPython==3.0.3
h5py==2.9.0
hendrics==5.0.dev0
hypothesis==4.43.5
identify==1.4.7
idna==2.7
imagesize==1.0.0
importlib-metadata==0.23
importlib-resources==1.0.2
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
jedi==0.12.1
Jinja2==2.10
jplephem==2.9
jsonschema==3.1.1
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.0
jupytext==1.2.4
kiwisolver==1.0.1
llvmlite==0.30.0
lxml==4.2.5
MarkupSafe==1.0
matplotlib==3.1.1
mccabe==0.6.1
mistune==0.8.4
mock==3.0.5
more-itertools==4.2.0
nbconvert==5.6.1
nbdime==1.1.0
nbformat==4.4.0
nbsphinx==0.4.3
netCDF4==1.2.9
nodeenv==1.3.3
nose==1.3.7
notebook==6.0.1
numba==0.46.0
numexpr==2.6.9
numpy==1.17.3
packaging==17.1
pandas==0.25.0
pandoc==1.0.2
pandocfilters==1.4.2
parso==0.3.0
pathspec==0.6.0
patsy==0.5.1
pdbpp==0.10.2
pep8-naming==0.9.0
pexpect==4.6.0
pickleshare==0.7.4
pint==0.5.4+433.g435a0e5
pluggy==0.13.0
ply==3.11
pre-commit==1.20.0
presto==3.0
prometheus-client==0.7.1
prompt-toolkit==2.0.10
ptyprocess==0.6.0
pwlf==1.1.0
py==1.5.4
pycodestyle==2.5.0
pydocstyle==4.0.1
pyDOE==0.3.8
pyflakes==2.1.1
Pygments==2.2.0
pyparsing==2.2.0
pyproj==1.9.5.1
PyQt5==5.12.1
PyQt5-sip==4.19.15
pyrsistent==0.15.4
pyshp==1.2.12
PySide2==5.12.2
pySLALIB==1.0.4
pytest==5.2.2
pytest-cov==2.8.1
pytest-runner==5.2
python-dateutil==2.7.3
pytz==2018.5
PyYAML==5.1.2
pyzmq==18.1.0
qtconsole==4.5.5
regex==2019.11.1
requests==2.19.1
restructuredtext-lint==1.3.0
scipy==1.3.1
Send2Trash==1.5.0
shiboken2==5.12.2
simplegeneric==0.8.1
six==1.11.0
smmap2==2.0.5
snowballstemmer==1.2.1
Sphinx==2.2.1
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.0
SQLAlchemy==1.3.6
statsmodels==0.10.2
stingray==0.1
tables==3.5.2
terminado==0.8.2
testpath==0.4.2
toml==0.10.0
tornado==6.0.3
tox==3.14.0
traitlets==4.3.2
typed-ast==1.4.0
urllib3==1.23
virtualenv==16.7.5
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.5.1
wmctrl==0.3
zipp==0.6.0
```

**Comment by paulray** [comment]
The above config is working. The only change was to netCDF4. With the later version readevents crashed on any NICER file, as shown above.

**Comment by matteobachetti** [comment]
@paulray Should be fixed. There is a problem in the order the libraries are imported, netcdf tries to use its own version of HDF5 that conflicts with the one imported by astropy. I worked around it importing netcdf in __init__.py as the very first thing.
